### ISSUE TITLE
Error creating shader on Windows11

### ISSUE THREAD

**Issue by IStrangers** [danfragoso/thdwb#38]
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
signal arrived during external code execution

runtime.cgocall(0xab1c30, 0xc000109c28)
	D:/go1.19.1/go1.19.1/src/runtime/cgocall.go:158 +0x4a fp=0xc000109c00 sp=0xc000109bc8 pc=0x704e8a
github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowCreateShader(0x0, 0x8b31)
	_cgo_gotypes.go:5527 +0x5a fp=0xc000109c28 sp=0xc000109c00 pc=0x88779a
github.com/go-gl/gl/v3.2-core/gl.CreateShader(...)
	C:/Users/15306/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20211210172815-726fda9656d6/v3.2-core/gl/package.go:9310
github.com/danfragoso/thdwb/mustard.compileShader({0xbe664c, 0x9b}, 0x761e07?)
	C:/Users/15306/Desktop/thdwb/mustard/shaders.go:39 +0x4a fp=0xc000109cd0 sp=0xc000109c28 pc=0x8a522a
github.com/danfragoso/thdwb/mustard.createNewGLProgram({0xbe664c?, 0xacef30?}, {0xbe65bb, 0x91})
	C:/Users/15306/Desktop/thdwb/mustard/gl.go:21 +0x3a fp=0xc000109d58 sp=0xc000109cd0 pc=0x8a30fa
github.com/danfragoso/thdwb/mustard.createGLBackend()
	C:/Users/15306/Desktop/thdwb/mustard/gl.go:56 +0x45 fp=0xc000109de8 sp=0xc000109d58 pc=0x8a34e5
github.com/danfragoso/thdwb/mustard.CreateNewWindow({0xbc1036, 0x5}, 0x384, 0x258, 0x1)
	C:/Users/15306/Desktop/thdwb/mustard/window.go:52 +0x29d fp=0xc000109e78 sp=0xc000109de8 pc=0x8a825d
main.main()
	C:/Users/15306/Desktop/thdwb/browser/main.go:46 +0x2c7 fp=0xc000109f80 sp=0xc000109e78 pc=0xaabc27
runtime.main()
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:250 +0x1fe fp=0xc000109fe0 sp=0xc000109f80 pc=0x73c01e
runtime.goexit()
	D:/go1.19.1/go1.19.1/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000109fe8 sp=0xc000109fe0 pc=0x766f61

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:363 +0xd6 fp=0xc000047fb0 sp=0xc000047f90 pc=0x73c3b6
runtime.goparkunlock(...)
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:369
runtime.forcegchelper()
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:302 +0xb1 fp=0xc000047fe0 sp=0xc000047fb0 pc=0x73c251
runtime.goexit()
	D:/go1.19.1/go1.19.1/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x766f61
created by runtime.init.6
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:363 +0xd6 fp=0xc000049f90 sp=0xc000049f70 pc=0x73c3b6
runtime.goparkunlock(...)
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	D:/go1.19.1/go1.19.1/src/runtime/mgcsweep.go:278 +0x8e fp=0xc000049fc8 sp=0xc000049f90 pc=0x7267ee
runtime.gcenable.func1()
	D:/go1.19.1/go1.19.1/src/runtime/mgc.go:178 +0x26 fp=0xc000049fe0 sp=0xc000049fc8 pc=0x71b386
runtime.goexit()
	D:/go1.19.1/go1.19.1/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000049fe8 sp=0xc000049fe0 pc=0x766f61
created by runtime.gcenable
	D:/go1.19.1/go1.19.1/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000012620?, 0xc7ab18?, 0x1?, 0x0?, 0x0?)
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:363 +0xd6 fp=0xc000059f70 sp=0xc000059f50 pc=0x73c3b6
runtime.goparkunlock(...)
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:369
runtime.(*scavengerState).park(0xf4e3a0)
	D:/go1.19.1/go1.19.1/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000059fa0 sp=0xc000059f70 pc=0x724873
runtime.bgscavenge(0x0?)
	D:/go1.19.1/go1.19.1/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000059fc8 sp=0xc000059fa0 pc=0x724e65
runtime.gcenable.func2()
	D:/go1.19.1/go1.19.1/src/runtime/mgc.go:179 +0x26 fp=0xc000059fe0 sp=0xc000059fc8 pc=0x71b326
runtime.goexit()
	D:/go1.19.1/go1.19.1/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x766f61
created by runtime.gcenable
	D:/go1.19.1/go1.19.1/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0xf4ea00?, 0xc000044ea0?, 0x0?, 0x0?, 0xc00004bf70?)
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:363 +0xd6 fp=0xc00004be28 sp=0xc00004be08 pc=0x73c3b6
runtime.goparkunlock(...)
	D:/go1.19.1/go1.19.1/src/runtime/proc.go:369
runtime.runfinq()
	D:/go1.19.1/go1.19.1/src/runtime/mfinal.go:180 +0x10f fp=0xc00004bfe0 sp=0xc00004be28 pc=0x71a48f
runtime.goexit()
	D:/go1.19.1/go1.19.1/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004bfe8 sp=0xc00004bfe0 pc=0x766f61
created by runtime.createfing
	D:/go1.19.1/go1.19.1/src/runtime/mfinal.go:157 +0x45
rax     0xc00010a000
rbx     0xc000109c28
rcx     0x8b31
rdi     0xc00010a000
rsi     0xf4e6a0
rbp     0xc000109bf0
rsp     0x8ee89ff6a8
r8      0xf4ea00
r9      0x0
r10     0x146f
r11     0x7ffa5f620710
r12     0xc000109ca8
r13     0x140
r14     0xc000044000
r15     0x2030000
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by IStrangers** [comment]
Put gl.Init() behind glw.MakeContextCurrent() to run
![R`P930Put gl.Init() behind glw.MakeContextCurrent() to run
OBR@729J(XDL1@B](https://user-images.githubusercontent.com/55904344/192412542-fedb3b88-f05a-4742-bce3-63a9443d1b4a.png)
